cmake_minimum_required(VERSION 3.22)
project(QuestMapBrowser)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(EXISTS "${CMAKE_SOURCE_DIR}/qpm_defines.cmake")
  include(${CMAKE_SOURCE_DIR}/qpm_defines.cmake)
endif()
if(EXISTS "${CMAKE_SOURCE_DIR}/extern.cmake")
  include(${CMAKE_SOURCE_DIR}/extern.cmake)
endif()
include(${CMAKE_SOURCE_DIR}/extern/beatsaber-hook/shared/utils.cmake)
file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS src/*.cpp shared/*.cpp)
add_library(questmap-browser SHARED ${SOURCES})
target_include_directories(questmap-browser PRIVATE include extern shared)
if(TARGET bsml)
  target_link_libraries(questmap-browser PRIVATE bsml)
endif()
target_link_libraries(questmap-browser PRIVATE log android)
quest_lib(questmap-browser)
